version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk-network
networks:
  elk-network:
    driver: bridge
